# Generated by Django 4.2.14 on 2024-07-19 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exercises", "0007_exercise_parts"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dataset",
                    models.FileField(blank=True, null=True, upload_to="model/"),
                ),
                ("isPositive", models.BooleanField(default=False)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exercises.exercise",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModelInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.FileField(blank=True, null=True, upload_to="model/")),
                ("valLoss", models.FloatField(default=69)),
                ("valAccuracy", models.FloatField(default=60)),
                (
                    "datasetID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="models.dataset"
                    ),
                ),
            ],
        ),
    ]
