# Generated by Django 4.2.14 on 2024-07-19 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0007_exercise_parts"),
        ("models", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modelinfo",
            name="datasetID",
        ),
        migrations.AddField(
            model_name="modelinfo",
            name="exercise",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="exercises.exercise",
            ),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="dataset",
            field=models.FileField(blank=True, null=True, upload_to="datasets/"),
        ),
    ]
