# Generated by Django 5.1 on 2024-10-12 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0020_exercise_numexecution_exercise_numset"),
        ("models", "0002_dataset_numdata_alter_dataset_dataset_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taskId", models.CharField(max_length=255, unique=True)),
                ("status", models.CharField(default="PENDING", max_length=50)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("progress", models.FloatField(default=0.0)),
                (
                    "exercise",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_training",
                        to="exercises.exercise",
                    ),
                ),
            ],
        ),
    ]
