# Generated by Django 4.2.14 on 2024-07-19 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0007_exercise_parts"),
        ("models", "0002_remove_modelinfo_datasetid_modelinfo_exercise_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ModelInfo",
            new_name="Model",
        ),
    ]
