# Generated by Django 5.1 on 2024-10-17 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0003_trainingprogress"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainingprogress",
            name="progress",
        ),
    ]
