# Generated by Django 4.2.14 on 2024-07-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0004_alter_dataset_dataset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="model",
            field=models.CharField(default="FILE PATH TEST", max_length=100),
        ),
    ]
