# Generated by Django 4.2.14 on 2024-07-31 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0007_exercise_parts"),
        ("models", "0007_alter_dataset_exercise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="exercise",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="model",
                to="exercises.exercise",
            ),
        ),
    ]
