# Generated by Django 4.2.14 on 2024-08-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0008_alter_model_exercise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="model",
            field=models.FileField(upload_to="models/"),
        ),
    ]
