# Generated by Django 4.1 on 2024-07-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="account",
            name="user_permissions",
        ),
        migrations.AddField(
            model_name="account",
            name="userType",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
