# Generated by Django 5.1 on 2024-08-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_account_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="height",
            field=models.IntegerField(default=69),
        ),
        migrations.AddField(
            model_name="account",
            name="weight",
            field=models.IntegerField(default=69),
        ),
    ]
