# Generated by Django 5.1 on 2024-08-26 01:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_account_height_account_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="height",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("69.00"), max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="weight",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("69.00"), max_digits=5
            ),
        ),
    ]
