# Generated by Django 4.2.14 on 2024-07-19 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workouts", "0004_alter_workout_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutsDone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("performed_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "workout",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workouts.workout",
                    ),
                ),
            ],
        ),
    ]
