# Generated by Django 4.2.14 on 2024-07-19 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutsdone",
            name="performed_at",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
