# Generated by Django 4.2.14 on 2024-07-19 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("history", "0003_alter_workoutsdone_performed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutsdone",
            name="account",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
