# Generated by Django 5.1 on 2024-08-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0005_favoriteworkout_favoriteexercise"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutsdone",
            name="calories_burned",
            field=models.IntegerField(default=69),
        ),
        migrations.AddField(
            model_name="workoutsdone",
            name="time_spent",
            field=models.IntegerField(default=69),
        ),
    ]
