# Generated by Django 4.2.14 on 2024-07-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0003_workoutfavorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
