# Generated by Django 4.2.14 on 2024-07-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0004_alter_workout_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
