# Generated by Django 4.2.14 on 2024-07-22 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0005_workout_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="difficulty",
            field=models.CharField(default="Medium", max_length=100),
        ),
    ]
