# Generated by Django 5.1 on 2024-08-12 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0006_workout_difficulty"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WorkoutFavorite",
        ),
    ]
