# Generated by Django 5.1 on 2024-09-25 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0008_workoutexercise_reps_workoutexercise_sets"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workoutexercise",
            name="reps",
        ),
        migrations.RemoveField(
            model_name="workoutexercise",
            name="sets",
        ),
    ]
