# Generated by Django 4.1 on 2024-07-16 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exercises", "0002_alter_exercise_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercisefavorite",
            name="description",
        ),
        migrations.RemoveField(
            model_name="exercisefavorite",
            name="estimated_time",
        ),
        migrations.RemoveField(
            model_name="exercisefavorite",
            name="image",
        ),
        migrations.RemoveField(
            model_name="exercisefavorite",
            name="intensity",
        ),
        migrations.RemoveField(
            model_name="exercisefavorite",
            name="name",
        ),
        migrations.RemoveField(
            model_name="exercisefavorite",
            name="uploaded_at",
        ),
        migrations.RemoveField(
            model_name="exercisefavorite",
            name="video",
        ),
        migrations.AddField(
            model_name="exercise",
            name="account",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="is_active",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name="exercisefavorite",
            name="account",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="exercisefavorite",
            name="exercise",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="exercises.exercise",
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="estimated_time",
            field=models.IntegerField(default=69, null=True),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="intensity",
            field=models.CharField(default="EZ AF", max_length=35),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="name",
            field=models.CharField(default="THIS IS THE NAME", max_length=100),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
