# Generated by Django 4.1 on 2024-07-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0005_alter_exercise_ignorecoordinates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="is_custom",
            field=models.BooleanField(default=True),
        ),
    ]
