# Generated by Django 4.2.14 on 2024-07-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0006_alter_exercise_is_active_alter_exercise_is_custom"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="parts",
            field=models.CharField(default="THIS IS A PART", max_length=100),
        ),
    ]
