# Generated by Django 5.1 on 2024-08-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0007_exercise_parts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="estimated_time",
        ),
        migrations.AddField(
            model_name="exercise",
            name="MET",
            field=models.IntegerField(default=69),
        ),
        migrations.AddField(
            model_name="exercise",
            name="base_calories_burn",
            field=models.IntegerField(default=69),
        ),
    ]
