# Generated by Django 5.1 on 2024-08-18 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0008_remove_exercise_estimated_time_exercise_met_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exercise",
            old_name="base_calories_burn",
            new_name="time_spent",
        ),
    ]
