# Generated by Django 5.1 on 2024-08-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0009_rename_base_calories_burn_exercise_time_spent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="time_spent",
        ),
        migrations.AddField(
            model_name="exercise",
            name="estimated_time",
            field=models.IntegerField(default=69, null=True),
        ),
    ]
