# Generated by Django 5.1 on 2024-09-23 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0010_remove_exercise_time_spent_exercise_estimated_time"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="estimated_time",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="numExecution",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="numSet",
        ),
        migrations.CreateModel(
            name="ExercisePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reps", models.IntegerField(default=69)),
                ("sets", models.IntegerField(default=69)),
                (
                    "account",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exercises.exercise",
                    ),
                ),
            ],
        ),
    ]
