# Generated by Django 5.1 on 2024-09-23 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0011_remove_exercise_estimated_time_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExercisePlan",
        ),
    ]
