# Generated by Django 5.1 on 2024-09-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0012_delete_exerciseplan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="parts",
            field=models.CharField(default="[Neck,Shoulder]", max_length=100),
        ),
    ]
