# Generated by Django 5.1 on 2024-09-23 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0013_alter_exercise_parts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="parts",
        ),
    ]
