# Generated by Django 5.1 on 2024-09-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0016_remove_exercise_parts"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="parts",
            field=models.CharField(default='["Neck","Shoulder"]', max_length=100),
        ),
    ]
