# Generated by Django 5.1 on 2024-09-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0017_exercise_parts"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="numExecution",
            field=models.IntegerField(default=69),
        ),
        migrations.AddField(
            model_name="exercise",
            name="numSet",
            field=models.IntegerField(default=69),
        ),
    ]
