# Generated by Django 5.1 on 2024-09-26 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0018_exercise_numexecution_exercise_numset"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="numExecution",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="numSet",
        ),
    ]
