# Generated by Django 5.1 on 2024-10-21 04:51

import exercises.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0020_exercise_numexecution_exercise_numset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="parts",
            field=models.JSONField(default=exercises.models.get_default_parts),
        ),
    ]
