# Generated by Django 5.1 on 2024-10-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0021_alter_exercise_is_active_alter_exercise_parts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="parts",
            field=models.JSONField(default=list),
        ),
    ]
